In [122]:
import numpy

In [123]:
nx = 81
dx = 0.25
dt = 0.0002
gamma = 1.4

In [124]:
x = numpy.linspace(-10, 10, nx)

In [125]:
#initial condition
rho_0 = numpy.empty_like(x)
u_0 = numpy.empty_like(x)
p_0 = numpy.empty_like(x)
counter = 0
for i in x:
    
    if i<=0:
        rho_0[counter] = 1.
        u_0[counter] = 0.
        p_0[counter] = 100.
    else:
        rho_0[counter] = 0.125
        u_0[counter] = 0.
        p_0[counter] = 10.
        
    counter = counter+1
    

In [126]:
def computeeT(p, rho, u, gamma):
    e = p/(rho*(gamma-1))
    eT = p/(rho*(gamma-1))+0.5 * u**2
    return eT

In [127]:
e_T = computeeT(p_0, rho_0, u_0, gamma)

In [128]:
u = numpy.zeros((3, nx))
u_1 = rho_0
u_2 = rho_0*u_0
u_3 = rho_0*e_T
u[0,] = u_1
u[1,] = u_2
u[2,] = u_3

In [129]:
def computef(u):
    f = numpy.zeros_like(u)
    u_1 = u[0,]
    u_2 = u[1,]
    u_3 = u[2,]
    
    f[0,] = u_2
    f[1,] = u_2**2/u_1 + (gamma - 1)*(u_3- 0.5*u_2**2/u_1)
    f[2,] = (u_3 + (gamma - 1)*(u_3 - 0.5*u_2**2/u_1))*u_2/u_1
    return f

In [130]:
un = numpy.zeros_like(u)
uplus = numpy.zeros_like(u)
fplus = numpy.zeros_like(u)
f = numpy.zeros_like(u)


for n in range (50):
    un = u.copy()
    f = computef(u)
    uplus[:,1:] = 0.5*(un[:,1:] + un[:,:-1]) - dt/(2*dx) *(f[:,1:]-f[:,:-1])
    uplus[:,0] = u[:,0]
    fplus = computef(uplus)
    u[:,1:-1] = un[:,1:-1] - dt/dx * (fplus[:,2:] - fplus[:,1:-1])


In [131]:
u[0]

array([ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        0.99999989,  0.9999998 ,  0.99992703,  0.99993144,  0.98289952,
        0.98124165,  0.14300731,  0.14250708,  0.12542519,  0.1250604 ,
        0.12500061,  0.12500007,  0.125     ,  0.125     ,  0.125     ,
        0.125     ,  0.125     ,  0.125     ,  0.125     ,  0.125     ,
        0.125     ,  0.125     ,  0.125     ,  0.125     ,  0.125     ,
        0.125     ,  0.125     ,  0.125     ,  0.125     ,  0.125     ,
        0.125     ,  0.125     ,  0.125     ,  0.125     ,  0.12

In [132]:
u[1]

array([  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         7.43511919e-15,   4.42241799e-14,   2.25939857e-11,
         8.56553243e-11,   4.00635059e-08,   9.19750757e-08,
         3.77420729e-05,   4.81510412e-05,   1.54303509e-02,
         1.07244384e-02,   1.71051861e+00,   1.76493393e+00,
         8.51548503e-02,   1.29355414e-02,   1.91226800e-04,
         2.48220264e-05,   1.85923947e-07,   2.09205563e-08,
         9.92244949e-11,

In [133]:
u[2]

array([ 250.        ,  250.        ,  250.        ,  250.        ,
        250.        ,  250.        ,  250.        ,  250.        ,
        250.        ,  250.        ,  250.        ,  250.        ,
        250.        ,  250.        ,  250.        ,  250.        ,
        250.        ,  250.        ,  250.        ,  250.        ,
        250.        ,  250.        ,  250.        ,  250.        ,
        250.        ,  250.        ,  250.        ,  250.        ,
        250.        ,  250.        ,  250.        ,  250.        ,
        250.        ,  249.99999997,  249.99999991,  249.99996026,
        249.99993124,  249.97446215,  249.9761134 ,  244.03703542,
        243.70211036,   32.11228955,   30.05934027,   25.12164645,
         25.01691855,   25.00017153,   25.00002082,   25.00000012,
         25.00000001,   25.        ,   25.        ,   25.        ,
         25.        ,   25.        ,   25.        ,   25.        ,
         25.        ,   25.        ,   25.        ,   25.     

In [142]:
for i in range (len(x)):
    if x[i] == 2.5:
        print (i)
        print(u[0,i])
        print(u[1,i])
        print(u[2,i])
        print(u[1,i]/u[0,i])

50
0.125
3.2109426229e-14
25.0
2.56875409832e-13


In [143]:
pp = (gamma - 1)*(u[2,50]-0.5*(u[1,50]**2/u[0,50]))
pp

10.000000000001727