In [84]:
import numpy

In [85]:
nx = 81
dx = 0.25
dt = 0.0002
gamma = 1.4

In [86]:
x = numpy.linspace(-10, 10, nx)

In [98]:
x

array([-10.  ,  -9.75,  -9.5 ,  -9.25,  -9.  ,  -8.75,  -8.5 ,  -8.25,
        -8.  ,  -7.75,  -7.5 ,  -7.25,  -7.  ,  -6.75,  -6.5 ,  -6.25,
        -6.  ,  -5.75,  -5.5 ,  -5.25,  -5.  ,  -4.75,  -4.5 ,  -4.25,
        -4.  ,  -3.75,  -3.5 ,  -3.25,  -3.  ,  -2.75,  -2.5 ,  -2.25,
        -2.  ,  -1.75,  -1.5 ,  -1.25,  -1.  ,  -0.75,  -0.5 ,  -0.25,
         0.  ,   0.25,   0.5 ,   0.75,   1.  ,   1.25,   1.5 ,   1.75,
         2.  ,   2.25,   2.5 ,   2.75,   3.  ,   3.25,   3.5 ,   3.75,
         4.  ,   4.25,   4.5 ,   4.75,   5.  ,   5.25,   5.5 ,   5.75,
         6.  ,   6.25,   6.5 ,   6.75,   7.  ,   7.25,   7.5 ,   7.75,
         8.  ,   8.25,   8.5 ,   8.75,   9.  ,   9.25,   9.5 ,   9.75,  10.  ])

In [87]:
#initial condition
rho_0 = numpy.empty_like(x)
u_0 = numpy.empty_like(x)
p_0 = numpy.empty_like(x)
counter = 0
for i in x:
    
    if i<=0:
        rho_0[counter] = 1.
        u_0[counter] = 0.
        p_0[counter] = 100.
    else:
        rho_0[counter] = 0.125
        u_0[counter] = 0.
        p_0[counter] = 10.
        
    counter = counter+1
    

In [88]:
def computeeT(p, rho, u, gamma):
    e = p/(rho*(gamma-1))
    eT = p/(rho*(gamma-1))+0.5 * u**2
    return eT

In [96]:
e_T = computeeT(p_0, rho_0, u_0, gamma)

In [100]:
e_T

array([ 250.,  250.,  250.,  250.,  250.,  250.,  250.,  250.,  250.,
        250.,  250.,  250.,  250.,  250.,  250.,  250.,  250.,  250.,
        250.,  250.,  250.,  250.,  250.,  250.,  250.,  250.,  250.,
        250.,  250.,  250.,  250.,  250.,  250.,  250.,  250.,  250.,
        250.,  250.,  250.,  250.,  250.,  200.,  200.,  200.,  200.,
        200.,  200.,  200.,  200.,  200.,  200.,  200.,  200.,  200.,
        200.,  200.,  200.,  200.,  200.,  200.,  200.,  200.,  200.,
        200.,  200.,  200.,  200.,  200.,  200.,  200.,  200.,  200.,
        200.,  200.,  200.,  200.,  200.,  200.,  200.,  200.,  200.])

In [90]:
u = numpy.zeros((3, nx))
u_1 = rho_0
u_2 = rho_0*u_0
u_3 = rho_0*e_T
u[0,] = u_1
u[1,] = u_2
u[2,] = u_3

In [91]:
def computef(u):
    f = numpy.zeros_like(u)
    u_1 = u[0,]
    u_2 = u[1,]
    u_3 = u[2,]
    
    f[0,] = u_2
    f[1,] = u_2**2/u_1 + (gamma - 1)*(u_3- 0.5*u_2**2/u_1)
    f[2,] = (u_3 + (gamma - 1)*(u_3 - 0.5*u_2**2/u_1))*u_2/u_1
    return f

In [92]:
un = numpy.zeros_like(u)
uplus = numpy.zeros_like(u)
fplus = numpy.zeros_like(u)
f = numpy.zeros_like(u)


for n in range (50):
    un = u.copy
    f = computef(u)
    uplus[:,1:] = 0.5*(un[:,1:] + un[:,:-1]) - dt/(2*dx) *(f[:,1:]-f[:,:-1])
    fplus = computef(uplus)
    u[:,1:-1] = un[:,1:-1] - dt/dx * (fplus[:,2:] - fplus[:,1:-1])


TypeError: 'builtin_function_or_method' object is not subscriptable

In [94]:
u

array([[  1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.25000000e-01,
          1.25000000e-01,   1.25000000e-01,   1.25000000e-01,
          1.25000000e-01,   1.25000000e-01,   1.25000000e-01,
        

In [57]:
un = numpy.empty_like(u)
for n in range(nx):
un = u.copy
f = computef(u)
uplus[,1:] = 0.5*(u[,:-1]+u[,1:])- dt/(2*dx) * (f[,1:]-f[,:-1])
uminus[,:-1] = 0.5*(u[,:-1]+u[,1:])- dt/(2*dx) * (f[,1:]-f[,:-1])
fplus = computef(uplus)
fminus = computef(uminus)
u[,1:] = un[,1:] - dt/dx * (fplus[,1:] - fplus[,:-1])

IndentationError: expected an indented block (<ipython-input-57-07f584324395>, line 3)

In [108]:
aa = numpy.zeros((3,3))
bb = numpy.zeros((5,5))
cc = [aa,bb]

dd = numpy.ones((3,3))
ee = numpy.ones((5,5))
ff = [dd,ee]

In [110]:
cc+ff

[array([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]), array([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]])]

In [107]:
dd = numpy.zeros(3,3,3)

TypeError: data type not understood