In [1]:
import numpy

In [11]:
nx = 41
ny = 41

l = 1.
h = 1.

dx = l/(nx-1)
dy = h/(ny-1)

target = 1e-6
u = 1

In [12]:
w = numpy.zeros((nx,ny))
w

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [13]:
psi = numpy.zeros_like(w)
psi[-1,1:-1] = 1/4*(2*psi[-2,1:-1] + psi[-1,2:] + psi[-1,:-2] +2*dy)
psi[-1,0] = psi[-1,1]
psi[-1,-1] = psi[-1,-2]
psi

array([[ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
       ..., 
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
       [ 0.0125,  0.0125,  0.0125, ...,  0.0125,  0.0125,  0.0125]])

In [14]:
def L1norm(new, old):
    norm = numpy.sum(numpy.abs(new-old))
    return norm

In [15]:
wuchaw = 1
wuchapsi = 1

In [20]:
while wuchaw>target and wuchapsi>target:
    

    
    wn = w.copy()
    w[1:-1,1:-1] = 0.25*(wn[1:-1,2:] + wn[1:-1, :-2] + wn[2:, 1:-1] + wn[:-2, 1:-1])
    w[-1,:] = -1/(2*dy**2) * (8*psi[-2,:] - psi[-3,:]) - 3*u/dy
       
    wuchaw = L1norm(w,wn)
    
    psin = psi.copy()
    psi[1:-1,1:-1] = 1/(2*(dx**2 + dy**2))*((psin[1:-1,2:]+psin[1:-1,:-2])*dy**2 +\
                                               (psin[2:,1:-1] +psin[:-2,1:-1])*dx**2 -\
                                               wn[1:-1, 1:-1]*dx**2 *dy**2)
    psi[-1,1:-1] = 1/4*(2*psi[-2,1:-1] + psi[-1,2:] + psi[-1,:-2] +2*dy)
    psi[-1,0] = psi[-1,1]
    psi[-1,-1] = psi[-1,-2]
    wuchapsi = L1norm(psi, psin)

In [21]:
w

array([[  0.00000000e+000,   0.00000000e+000,   0.00000000e+000, ...,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,  -7.13153187e+294,  -1.42190955e+295, ...,
         -1.42190955e+295,  -7.13153187e+294,   0.00000000e+000],
       [  0.00000000e+000,  -1.79720458e+295,  -3.58332879e+295, ...,
         -3.58332879e+295,  -1.79720458e+295,   0.00000000e+000],
       ..., 
       [  0.00000000e+000,  -2.11466454e+306,  -4.21629147e+306, ...,
         -4.21629147e+306,  -2.11466454e+306,   0.00000000e+000],
       [  0.00000000e+000,  -4.28570441e+306,  -8.54498602e+306, ...,
         -8.54498602e+306,  -4.28570441e+306,   0.00000000e+000],
       [ -1.20000000e+002,  -8.68566239e+306,  -1.73177748e+307, ...,
         -1.73177748e+307,  -8.68566239e+306,  -1.20000000e+002]])

In [22]:
psi

array([[  0.00000000e+000,   0.00000000e+000,   0.00000000e+000, ...,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   1.11504185e+293,   2.22320910e+293, ...,
          2.22320910e+293,   1.11504185e+293,   0.00000000e+000],
       [  0.00000000e+000,   2.76542492e+293,   5.51380008e+293, ...,
          5.51380008e+293,   2.76542492e+293,   0.00000000e+000],
       ..., 
       [  0.00000000e+000,   1.72402034e+303,   3.43741152e+303, ...,
          3.43741152e+303,   1.72402034e+303,   0.00000000e+000],
       [  0.00000000e+000,   1.74700086e+303,   3.48323089e+303, ...,
          3.48323089e+303,   1.74700086e+303,   0.00000000e+000],
       [  1.25000000e-002,   1.25000000e-002,   1.25000000e-002, ...,
          1.25000000e-002,   1.25000000e-002,   1.25000000e-002]])

In [26]:
numpy.round(psi[32,::8], 4)

array([  0.00000000e+000,   7.45578505e+302,   1.20637136e+303,
         1.20637136e+303,   7.45578505e+302,   0.00000000e+000])

In [25]:
max(numpy.abs(psi))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
def assignment_5(w, psi, target ):
    wn = w.copy()
    psin = psi.copy()
    wuchaw = 1
    wuchapsi = 1
    
    while wuchaw<target and wuchapsi<target:
        wn = w.copy
        w[1:-1,1:-1] = 0.25*(wn[1:-1,2:] + wn[1:-1, :-2] + wn[2:, 1:-1] + wn[:-2, 1:-1])
        w[-1,:] = -1/(2*dy**2) * (8*psi[-2,:] - psi[-3,:]) - 3*u/dy
        
        wuchaw = L1norm(w,wn)
        
        psin = psi.copy()
        psi[1:-1,1:-1] = 1/(2*(dx**2 + dy**2))*((psin[1:-1,2:]+psin[1:-1,:-2])*dy**2 +\
                                               (psin[2:,1:-1] +psin[:-2,1:-1])*dx**2 -\
                                               wn[1:-1, 1:-1]*dx**2 *dy**2)
        wuchapsi = Linorm(psi, psin)